theme = "onedark"

[editor]
idle-timeout = 0
cursorline = true
auto-save = true
auto-format = true
rulers = [80]

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
