theme = "dark_plus"

[editor]
true-color = true
idle-timeout = 0
cursorline = true
auto-save = true
auto-format = true
rulers = [80]
completion-replace = true
auto-info = false
line-number = "relative"
popup-border="all"

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
