[[language]]
name = "c"
indent = {tab-width = 4,unit = "\t"}
formatter = { command = "clang-format" ,args = [] }
auto-format = true

[[language]]
name = "cpp"
indent = {tab-width = 4,unit = "\t"}
formatter = { command = "clang-format" ,args = [] }
auto-format = true

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
